apiVersion: apps/v1
kind: Deployment
metadata:
  name: video procesing
  labels:
    app: video procesing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video procesing
  template:
    metadata:
      labels:
        app: video procesing
    spec:
      containers:
        - name: video procesing
          image: "username/video procesing:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
